apiVersion: v1
kind: List
items:
- apiVersion: primitives.federation.k8s.io/v1alpha1
  kind: FederatedConfigMapOverride
  metadata:
    name: test-configmap
    namespace: test-namespace
  spec:
    overrides:
    - clusterName: cwilkers2
      clusterOverrides:
      - path: data
        value:
          foo: bar
