apiVersion: primitives.federation.k8s.io/v1alpha1
kind: FederatedServicePlacement
metadata:
  name: test-service
  namespace: test-namespace
spec:
  clusterNames:
  - cwilkers3
  - cwilkers2
  - cwilkers1
