apiVersion: v1
kind: List
items:
- apiVersion: primitives.federation.k8s.io/v1alpha1
  kind: FederatedDeploymentOverride
  metadata:
    name: test-deployment
    namespace: test-namespace
  spec:
    overrides:
    - clusterName: cwilkers2
      clusterOverrides:
      - path: spec.replicas
        value: 5
