apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedIngress
  metadata:
    name: test-ingress
    namespace: test-namespace
  spec:
    template:
      spec:
        rules:
        - host: test.example.com
          http:
            paths:
            - path: /
              backend:
                serviceName: test-service
                servicePort: 80
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedIngressPlacement
  metadata:
    name: test-ingress
    namespace: test-namespace
  spec:
    clusterNames:
    - cluster1
    - cluster2
